name: scipy18jlab
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - cookiecutter
  - notebook
  - pandas=0.23
  - nodejs
  - jupyterlab
  - bqplot
  - ipyleaflet
  - ipympl
  - ipyvolume
  - pythreejs
